code --install-extesion amazonwebservices.aws-toolkit-vscode
code --install-extesion bigonesystems.django
code --install-extesion dbaeumer.vscode-eslint
code --install-extesion denoland.vscode-deno
code --install-extesion eamodio.gitlens
code --install-extesion github.copilot
code --install-extesion github.copilot-chat
code --install-extesion github.vscode-github-actions
code --install-extesion github.vscode-pull-request-github
code --install-extesion golang.go
code --install-extesion grapecity.gc-excelviewer
code --install-extesion hashicorp.terraform
code --install-extesion mechatroner.rainbow-csv
code --install-extesion ms-azuretools.vscode-docker
code --install-extesion ms-dotnettools.vscode-dotnet-runtime
code --install-extesion ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extesion ms-python.black-formatter
code --install-extesion ms-python.debugpy
code --install-extesion ms-python.python
code --install-extesion ms-python.vscode-pylance
code --install-extesion ms-toolsai.jupyter
code --install-extesion ms-toolsai.jupyter-keymap
code --install-extesion ms-toolsai.jupyter-renderers
code --install-extesion ms-toolsai.vscode-jupyter-cell-tags
code --install-extesion ms-toolsai.vscode-jupyter-slideshow
code --install-extesion ms-vscode-remote.remote-containers
code --install-extesion ms-vscode.makefile-tools
code --install-extesion msjsdiag.vscode-react-native
code --install-extesion msyrus.go-doc
code --install-extesion redhat.vscode-xml
code --install-extesion redhat.vscode-yaml
code --install-extesion stripe.vscode-stripe
code --install-extesion unifiedjs.vscode-mdx
code --install-extesion vue.volar
code --install-extesion zxh404.vscode-proto3
