#!/bin/bash
code --install-extension amazonwebservices.aws-toolkit-vscode --force
code --install-extension bigonesystems.django --force
code --install-extension dbaeumer.vscode-eslint --force
code --install-extension denoland.vscode-deno --force
code --install-extension eamodio.gitlens --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension github.vscode-github-actions --force
code --install-extension github.vscode-pull-request-github --force
code --install-extension golang.go --force
code --install-extension grapecity.gc-excelviewer --force
code --install-extension hashicorp.terraform --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-dotnettools.vscode-dotnet-runtime --force
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --force
code --install-extension ms-python.black-formatter --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode.makefile-tools --force
code --install-extension msjsdiag.vscode-react-native --force
code --install-extension msyrus.go-doc --force
code --install-extension redhat.vscode-xml --force
code --install-extension redhat.vscode-yaml --force
code --install-extension stripe.vscode-stripe --force
code --install-extension unifiedjs.vscode-mdx --force
code --install-extension vue.volar --force
code --install-extension zxh404.vscode-proto3 --force
